// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HyperlocalNews {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HyperlocalNews.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        internal static string IntroText {
            get {
                return ResourceManager.GetString("IntroText", resourceCulture);
            }
        }
        
        internal static string ConnectionErrorLabel {
            get {
                return ResourceManager.GetString("ConnectionErrorLabel", resourceCulture);
            }
        }
        
        internal static string SignUpLabel {
            get {
                return ResourceManager.GetString("SignUpLabel", resourceCulture);
            }
        }
        
        internal static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        internal static string TermsConditionsLabel {
            get {
                return ResourceManager.GetString("TermsConditionsLabel", resourceCulture);
            }
        }
        
        internal static string TermsConditionsText {
            get {
                return ResourceManager.GetString("TermsConditionsText", resourceCulture);
            }
        }
        
        internal static string JoinLabel {
            get {
                return ResourceManager.GetString("JoinLabel", resourceCulture);
            }
        }
        
        internal static string StartLabel {
            get {
                return ResourceManager.GetString("StartLabel", resourceCulture);
            }
        }
        
        internal static string FullNameLabel {
            get {
                return ResourceManager.GetString("FullNameLabel", resourceCulture);
            }
        }
        
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        internal static string ReportSubmittedTitle {
            get {
                return ResourceManager.GetString("ReportSubmittedTitle", resourceCulture);
            }
        }
        
        internal static string ReportSubmittedLabel {
            get {
                return ResourceManager.GetString("ReportSubmittedLabel", resourceCulture);
            }
        }
        
        internal static string ReportSavedTitle {
            get {
                return ResourceManager.GetString("ReportSavedTitle", resourceCulture);
            }
        }
        
        internal static string ReportSavedLabel {
            get {
                return ResourceManager.GetString("ReportSavedLabel", resourceCulture);
            }
        }
        
        internal static string LocationNeededTitle {
            get {
                return ResourceManager.GetString("LocationNeededTitle", resourceCulture);
            }
        }
        
        internal static string LocationNeededLabel {
            get {
                return ResourceManager.GetString("LocationNeededLabel", resourceCulture);
            }
        }
        
        internal static string SubmissionFailedTitle {
            get {
                return ResourceManager.GetString("SubmissionFailedTitle", resourceCulture);
            }
        }
        
        internal static string SubmissionFailedLabel {
            get {
                return ResourceManager.GetString("SubmissionFailedLabel", resourceCulture);
            }
        }
        
        internal static string DiscardLabel {
            get {
                return ResourceManager.GetString("DiscardLabel", resourceCulture);
            }
        }
        
        internal static string NewReportLabel {
            get {
                return ResourceManager.GetString("NewReportLabel", resourceCulture);
            }
        }
        
        internal static string SubmitLabel {
            get {
                return ResourceManager.GetString("SubmitLabel", resourceCulture);
            }
        }
        
        internal static string SubmitLabelAlternative {
            get {
                return ResourceManager.GetString("SubmitLabelAlternative", resourceCulture);
            }
        }
        
        internal static string DoneLabel {
            get {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }
        
        internal static string SaveAsDraftLabel {
            get {
                return ResourceManager.GetString("SaveAsDraftLabel", resourceCulture);
            }
        }
        
        internal static string ConfirmLabel {
            get {
                return ResourceManager.GetString("ConfirmLabel", resourceCulture);
            }
        }
        
        internal static string PreferredLanguageLabel {
            get {
                return ResourceManager.GetString("PreferredLanguageLabel", resourceCulture);
            }
        }
        
        internal static string ProfileUpdateAlertTitle {
            get {
                return ResourceManager.GetString("ProfileUpdateAlertTitle", resourceCulture);
            }
        }
        
        internal static string ProfileUpdateAlertLabel {
            get {
                return ResourceManager.GetString("ProfileUpdateAlertLabel", resourceCulture);
            }
        }
        
        internal static string ProfileUpdateAlertTitleREVERSE {
            get {
                return ResourceManager.GetString("ProfileUpdateAlertTitleREVERSE", resourceCulture);
            }
        }
        
        internal static string ProfileUpdateAlertLabelREVERSE {
            get {
                return ResourceManager.GetString("ProfileUpdateAlertLabelREVERSE", resourceCulture);
            }
        }
        
        internal static string OKLabelREVERSE {
            get {
                return ResourceManager.GetString("OKLabelREVERSE", resourceCulture);
            }
        }
        
        internal static string UpdateLabel {
            get {
                return ResourceManager.GetString("UpdateLabel", resourceCulture);
            }
        }
        
        internal static string UpdateFailedTitle {
            get {
                return ResourceManager.GetString("UpdateFailedTitle", resourceCulture);
            }
        }
        
        internal static string UpdateFailedLabel {
            get {
                return ResourceManager.GetString("UpdateFailedLabel", resourceCulture);
            }
        }
        
        internal static string BackLabel {
            get {
                return ResourceManager.GetString("BackLabel", resourceCulture);
            }
        }
        
        internal static string OKLabel {
            get {
                return ResourceManager.GetString("OKLabel", resourceCulture);
            }
        }
        
        internal static string SelectHyperlocalLabel {
            get {
                return ResourceManager.GetString("SelectHyperlocalLabel", resourceCulture);
            }
        }
        
        internal static string VerificationAlertTitle {
            get {
                return ResourceManager.GetString("VerificationAlertTitle", resourceCulture);
            }
        }
        
        internal static string VerificationAlertLabel {
            get {
                return ResourceManager.GetString("VerificationAlertLabel", resourceCulture);
            }
        }
        
        internal static string GuideLabel {
            get {
                return ResourceManager.GetString("GuideLabel", resourceCulture);
            }
        }
        
        internal static string ExportLabel {
            get {
                return ResourceManager.GetString("ExportLabel", resourceCulture);
            }
        }
        
        internal static string UserFeedbackResponse {
            get {
                return ResourceManager.GetString("UserFeedbackResponse", resourceCulture);
            }
        }
        
        internal static string JoinButtonLabel {
            get {
                return ResourceManager.GetString("JoinButtonLabel", resourceCulture);
            }
        }
        
        internal static string ClaimButtonLabel {
            get {
                return ResourceManager.GetString("ClaimButtonLabel", resourceCulture);
            }
        }
        
        internal static string DeclinedButtonLabel {
            get {
                return ResourceManager.GetString("DeclinedButtonLabel", resourceCulture);
            }
        }
        
        internal static string ClaimedPrefix {
            get {
                return ResourceManager.GetString("ClaimedPrefix", resourceCulture);
            }
        }
        
        internal static string ClaimedString {
            get {
                return ResourceManager.GetString("ClaimedString", resourceCulture);
            }
        }
        
        internal static string DeclinedString {
            get {
                return ResourceManager.GetString("DeclinedString", resourceCulture);
            }
        }
        
        internal static string HyperlocalDescriptionText {
            get {
                return ResourceManager.GetString("HyperlocalDescriptionText", resourceCulture);
            }
        }
        
        internal static string RegisterHyperlocalDescriptionText {
            get {
                return ResourceManager.GetString("RegisterHyperlocalDescriptionText", resourceCulture);
            }
        }
        
        internal static string RegisterNewHyperlocalSuggestion {
            get {
                return ResourceManager.GetString("RegisterNewHyperlocalSuggestion", resourceCulture);
            }
        }
        
        internal static string RegisterNewHyperlocalSuggestionHTML {
            get {
                return ResourceManager.GetString("RegisterNewHyperlocalSuggestionHTML", resourceCulture);
            }
        }
        
        internal static string HyperlocalTitle {
            get {
                return ResourceManager.GetString("HyperlocalTitle", resourceCulture);
            }
        }
        
        internal static string NewsSendTitle {
            get {
                return ResourceManager.GetString("NewsSendTitle", resourceCulture);
            }
        }
        
        internal static string RecoverTitle {
            get {
                return ResourceManager.GetString("RecoverTitle", resourceCulture);
            }
        }
        
        internal static string RecoverTitleAlt {
            get {
                return ResourceManager.GetString("RecoverTitleAlt", resourceCulture);
            }
        }
        
        internal static string RecoveryEmailText {
            get {
                return ResourceManager.GetString("RecoveryEmailText", resourceCulture);
            }
        }
        
        internal static string FeedbackLabel {
            get {
                return ResourceManager.GetString("FeedbackLabel", resourceCulture);
            }
        }
        
        internal static string DraftsLabel {
            get {
                return ResourceManager.GetString("DraftsLabel", resourceCulture);
            }
        }
        
        internal static string SentLabel {
            get {
                return ResourceManager.GetString("SentLabel", resourceCulture);
            }
        }
        
        internal static string ProfileLabel {
            get {
                return ResourceManager.GetString("ProfileLabel", resourceCulture);
            }
        }
        
        internal static string MeLabel {
            get {
                return ResourceManager.GetString("MeLabel", resourceCulture);
            }
        }
        
        internal static string ReportLabel {
            get {
                return ResourceManager.GetString("ReportLabel", resourceCulture);
            }
        }
        
        internal static string RequestLabel {
            get {
                return ResourceManager.GetString("RequestLabel", resourceCulture);
            }
        }
        
        internal static string HeadlineLabel {
            get {
                return ResourceManager.GetString("HeadlineLabel", resourceCulture);
            }
        }
        
        internal static string StoryCopyLabel {
            get {
                return ResourceManager.GetString("StoryCopyLabel", resourceCulture);
            }
        }
        
        internal static string ReportGuidelinesText {
            get {
                return ResourceManager.GetString("ReportGuidelinesText", resourceCulture);
            }
        }
        
        internal static string AdditionalInformationLabel {
            get {
                return ResourceManager.GetString("AdditionalInformationLabel", resourceCulture);
            }
        }
        
        internal static string PhotoLabel {
            get {
                return ResourceManager.GetString("PhotoLabel", resourceCulture);
            }
        }
        
        internal static string DateTimeLabel {
            get {
                return ResourceManager.GetString("DateTimeLabel", resourceCulture);
            }
        }
        
        internal static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        internal static string SendToLabel {
            get {
                return ResourceManager.GetString("SendToLabel", resourceCulture);
            }
        }
        
        internal static string NearbyHyperlocalLabel {
            get {
                return ResourceManager.GetString("NearbyHyperlocalLabel", resourceCulture);
            }
        }
        
        internal static string SendToLabelCombined {
            get {
                return ResourceManager.GetString("SendToLabelCombined", resourceCulture);
            }
        }
        
        internal static string YourHyperlocalLabel {
            get {
                return ResourceManager.GetString("YourHyperlocalLabel", resourceCulture);
            }
        }
        
        internal static string PatchPaperDescriptionLabel {
            get {
                return ResourceManager.GetString("PatchPaperDescriptionLabel", resourceCulture);
            }
        }
        
        internal static string JoinHyperlocalLabel {
            get {
                return ResourceManager.GetString("JoinHyperlocalLabel", resourceCulture);
            }
        }
        
        internal static string RegisterHyperlocalLabel {
            get {
                return ResourceManager.GetString("RegisterHyperlocalLabel", resourceCulture);
            }
        }
        
        internal static string HyperlocalNameLabel {
            get {
                return ResourceManager.GetString("HyperlocalNameLabel", resourceCulture);
            }
        }
        
        internal static string HyperlocalSearchLabel {
            get {
                return ResourceManager.GetString("HyperlocalSearchLabel", resourceCulture);
            }
        }
        
        internal static string LocationLabel2 {
            get {
                return ResourceManager.GetString("LocationLabel2", resourceCulture);
            }
        }
        
        internal static string AdministrationEmailLabel {
            get {
                return ResourceManager.GetString("AdministrationEmailLabel", resourceCulture);
            }
        }
        
        internal static string RegisterHyperlocalText {
            get {
                return ResourceManager.GetString("RegisterHyperlocalText", resourceCulture);
            }
        }
        
        internal static string EmailVerificationText {
            get {
                return ResourceManager.GetString("EmailVerificationText", resourceCulture);
            }
        }
        
        internal static string ReportTitleLabel {
            get {
                return ResourceManager.GetString("ReportTitleLabel", resourceCulture);
            }
        }
        
        internal static string ExportTitleLabel {
            get {
                return ResourceManager.GetString("ExportTitleLabel", resourceCulture);
            }
        }
        
        internal static string SendLabel {
            get {
                return ResourceManager.GetString("SendLabel", resourceCulture);
            }
        }
        
        internal static string TeamMessageLabel {
            get {
                return ResourceManager.GetString("TeamMessageLabel", resourceCulture);
            }
        }
        
        internal static string TeamMessageText {
            get {
                return ResourceManager.GetString("TeamMessageText", resourceCulture);
            }
        }
        
        internal static string YourReplyLabel {
            get {
                return ResourceManager.GetString("YourReplyLabel", resourceCulture);
            }
        }
        
        internal static string AdditionalLabel {
            get {
                return ResourceManager.GetString("AdditionalLabel", resourceCulture);
            }
        }
        
        internal static string SendFeedbackLabel {
            get {
                return ResourceManager.GetString("SendFeedbackLabel", resourceCulture);
            }
        }
        
        internal static string FeedbackSendTitle {
            get {
                return ResourceManager.GetString("FeedbackSendTitle", resourceCulture);
            }
        }
        
        internal static string FeedbackSentLabel {
            get {
                return ResourceManager.GetString("FeedbackSentLabel", resourceCulture);
            }
        }
        
        internal static string FeedbackFailedTitle {
            get {
                return ResourceManager.GetString("FeedbackFailedTitle", resourceCulture);
            }
        }
        
        internal static string FeedbackFailedLabel {
            get {
                return ResourceManager.GetString("FeedbackFailedLabel", resourceCulture);
            }
        }
        
        internal static string ArticleExplortedTitle {
            get {
                return ResourceManager.GetString("ArticleExplortedTitle", resourceCulture);
            }
        }
        
        internal static string ArticleExplortedLabel {
            get {
                return ResourceManager.GetString("ArticleExplortedLabel", resourceCulture);
            }
        }
        
        internal static string ArticleExplortFailedTitle {
            get {
                return ResourceManager.GetString("ArticleExplortFailedTitle", resourceCulture);
            }
        }
        
        internal static string ArticleExplortFailedLabel {
            get {
                return ResourceManager.GetString("ArticleExplortFailedLabel", resourceCulture);
            }
        }
        
        internal static string ArticleClaimRemovedTitle {
            get {
                return ResourceManager.GetString("ArticleClaimRemovedTitle", resourceCulture);
            }
        }
        
        internal static string ArticleClaimRemovedLabel {
            get {
                return ResourceManager.GetString("ArticleClaimRemovedLabel", resourceCulture);
            }
        }
        
        internal static string ArticleClaimedTitle {
            get {
                return ResourceManager.GetString("ArticleClaimedTitle", resourceCulture);
            }
        }
        
        internal static string ArticleClaimedLabel {
            get {
                return ResourceManager.GetString("ArticleClaimedLabel", resourceCulture);
            }
        }
        
        internal static string ArticleClaimFailedTitle {
            get {
                return ResourceManager.GetString("ArticleClaimFailedTitle", resourceCulture);
            }
        }
        
        internal static string ArticleClaimFailedLabel {
            get {
                return ResourceManager.GetString("ArticleClaimFailedLabel", resourceCulture);
            }
        }
        
        internal static string ArticleUndeclinedTitle {
            get {
                return ResourceManager.GetString("ArticleUndeclinedTitle", resourceCulture);
            }
        }
        
        internal static string ArticleUndeclinedLabel {
            get {
                return ResourceManager.GetString("ArticleUndeclinedLabel", resourceCulture);
            }
        }
        
        internal static string ArticleDeclinedTitle {
            get {
                return ResourceManager.GetString("ArticleDeclinedTitle", resourceCulture);
            }
        }
        
        internal static string ArticleDeclinedLabel {
            get {
                return ResourceManager.GetString("ArticleDeclinedLabel", resourceCulture);
            }
        }
        
        internal static string ArticleDeclineFailedTitle {
            get {
                return ResourceManager.GetString("ArticleDeclineFailedTitle", resourceCulture);
            }
        }
        
        internal static string ArticleDeclineFailedLabel {
            get {
                return ResourceManager.GetString("ArticleDeclineFailedLabel", resourceCulture);
            }
        }
        
        internal static string CannotRegisterTitle {
            get {
                return ResourceManager.GetString("CannotRegisterTitle", resourceCulture);
            }
        }
        
        internal static string CannotRegisterLabel {
            get {
                return ResourceManager.GetString("CannotRegisterLabel", resourceCulture);
            }
        }
        
        internal static string RegistrationRequestedTitle {
            get {
                return ResourceManager.GetString("RegistrationRequestedTitle", resourceCulture);
            }
        }
        
        internal static string RegistrationRequestedLabel {
            get {
                return ResourceManager.GetString("RegistrationRequestedLabel", resourceCulture);
            }
        }
        
        internal static string RegistrationRequestFailedTitle {
            get {
                return ResourceManager.GetString("RegistrationRequestFailedTitle", resourceCulture);
            }
        }
        
        internal static string RegistrationRequestFailedLabel {
            get {
                return ResourceManager.GetString("RegistrationRequestFailedLabel", resourceCulture);
            }
        }
        
        internal static string VerificationRequestedTitle {
            get {
                return ResourceManager.GetString("VerificationRequestedTitle", resourceCulture);
            }
        }
        
        internal static string VerificationRequestedLabel {
            get {
                return ResourceManager.GetString("VerificationRequestedLabel", resourceCulture);
            }
        }
        
        internal static string VerificationRequestFailedTitle {
            get {
                return ResourceManager.GetString("VerificationRequestFailedTitle", resourceCulture);
            }
        }
        
        internal static string VerificationRequestFailedLabel {
            get {
                return ResourceManager.GetString("VerificationRequestFailedLabel", resourceCulture);
            }
        }
        
        internal static string UserVerificationRequestProcessedTitle {
            get {
                return ResourceManager.GetString("UserVerificationRequestProcessedTitle", resourceCulture);
            }
        }
        
        internal static string UserVerificationRequestProcessedLabel {
            get {
                return ResourceManager.GetString("UserVerificationRequestProcessedLabel", resourceCulture);
            }
        }
        
        internal static string UserVerificationRequestFailedTitle {
            get {
                return ResourceManager.GetString("UserVerificationRequestFailedTitle", resourceCulture);
            }
        }
        
        internal static string UserVerificationRequestFailedLabel {
            get {
                return ResourceManager.GetString("UserVerificationRequestFailedLabel", resourceCulture);
            }
        }
        
        internal static string ProfileUpdatedTitle {
            get {
                return ResourceManager.GetString("ProfileUpdatedTitle", resourceCulture);
            }
        }
        
        internal static string ProfileUpdatedLabel {
            get {
                return ResourceManager.GetString("ProfileUpdatedLabel", resourceCulture);
            }
        }
        
        internal static string ProfileUpdatedTitleREVERSE {
            get {
                return ResourceManager.GetString("ProfileUpdatedTitleREVERSE", resourceCulture);
            }
        }
        
        internal static string ProfileUpdatedLabelREVERSE {
            get {
                return ResourceManager.GetString("ProfileUpdatedLabelREVERSE", resourceCulture);
            }
        }
        
        internal static string ProfileUpdateFailedTitle {
            get {
                return ResourceManager.GetString("ProfileUpdateFailedTitle", resourceCulture);
            }
        }
        
        internal static string ProfileUpdateFailedLabel {
            get {
                return ResourceManager.GetString("ProfileUpdateFailedLabel", resourceCulture);
            }
        }
        
        internal static string UserRegistrationFailedTitle {
            get {
                return ResourceManager.GetString("UserRegistrationFailedTitle", resourceCulture);
            }
        }
        
        internal static string UserRegistrationFailedLabel {
            get {
                return ResourceManager.GetString("UserRegistrationFailedLabel", resourceCulture);
            }
        }
        
        internal static string UserLoginFailReason {
            get {
                return ResourceManager.GetString("UserLoginFailReason", resourceCulture);
            }
        }
        
        internal static string FeedbackResponseFailedTitle {
            get {
                return ResourceManager.GetString("FeedbackResponseFailedTitle", resourceCulture);
            }
        }
        
        internal static string FeedbackResponseFailedLabel {
            get {
                return ResourceManager.GetString("FeedbackResponseFailedLabel", resourceCulture);
            }
        }
        
        internal static string FeedbackResponseSentTitle {
            get {
                return ResourceManager.GetString("FeedbackResponseSentTitle", resourceCulture);
            }
        }
        
        internal static string FeedbackResponseSentLabel {
            get {
                return ResourceManager.GetString("FeedbackResponseSentLabel", resourceCulture);
            }
        }
        
        internal static string UserVerifyScreenTitle {
            get {
                return ResourceManager.GetString("UserVerifyScreenTitle", resourceCulture);
            }
        }
        
        internal static string UserVerifyScreenMessage {
            get {
                return ResourceManager.GetString("UserVerifyScreenMessage", resourceCulture);
            }
        }
    }
}
